### ISSUE TITLE
Consider disabling zcash: URI scheme

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zashi-ios#1096]
This is @defuse's suggested mitigation for #1093 and #1094.

**Comment by LukasKorba** [comment]
Support for deplinks was impemented very long time ago, I think around mid 2022 because at the time it was a regular requirement but nobody defined actual and useful deeplinks. So the implementation is still in nowadays Zashi, doing:
- registering the URI
- parsing any URL that starts with `zcash://`

As a debug example sending some amount to a specific address URL was used but it's no longer valid because the infrastructure of nowadays Zashi changed. 

We have 2 options:
1. Disable the whole feature, it would mean delete the URI support but I would leave at least the deeplink YCA dependency module in place for possible future re-open of the feature.
2. Make a use of deeplinks, define some useful URLs.

Please NOTE, I agree that definition of the URI automatically allows some other apps to discover Zashi but we can't do anything about it, it's how it's designed. 

Title of this issue says `Consider disabling` like it's a solution for Zashi 1.0 but it's only postponing the issue to some other day in the future. Only ultimate solution is to never use URI and deeplinks on iOS and that I can't decided, I don't know if product/leadeship will ever make such call.

**Comment by daira** [comment]
> Title of this issue says Consider disabling like it's a solution for Zashi 1.0 but it's only postponing the issue to some other day in the future. Only ultimate solution is to never use URI and deeplinks on iOS and that I can't decide, I don't know if product/leadership will ever make such call.

Yes it sucks. It would basically mean abandoning ZIP 321. But I want everyone to know that I am very serious about deprecating/removing features that can't in practice be made secure, even if we have expended a lot of work on them.

**Comment by pacu** [comment]
> It would basically mean abandoning ZIP 321
Not actually. The Zashi app can choose not to tell the OS that it can handle the URI, but in fact handle it internally when scanning it from a QR or receiving a share item that contains a payment URI in the form of text. The UX wouldn't be  "automagical" like Apple likes it but Zcash's mission is not to be super lean at any cost.
