### ISSUE TITLE
Xcode 15.3 Build Error.

### ISSUE THREAD

**Issue by pacu** [Electric-Coin-Company/zashi-ios#1166]
### Describe the issue
When building Zashi with Xcode 15.3 the following error occurs.

<img width="458" alt="image" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/484008/11ebd125-4132-4659-9ec8-a5c49fac7f09">

#### If so, please list the steps to reproduce below:
1. Get Xcode 15.3
2. Select a simulator platform as target
3. Build and Run

### Expected behaviour
It should build.

### Actual behaviour + errors
<img width="458" alt="image" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/484008/88fbae1a-cbc2-4133-bd7c-d7d8b0656854">

macOS Version 14.4.1 (Build 23E224)
Xcode 15.3 (22618) (Build 15E204a)

### Any extra information that might be useful in the debugging process.
Anton from unstoppable also reported this issue to me 

```
--
Unable to Install “Unstoppable D”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ET3U8b/extracted/Unstoppable D.app/Frameworks/libzcashlc.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ET3U8b/extracted/Unstoppable D.app/Frameworks/libzcashlc.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ET3U8b/extracted/Unstoppable D.app/Frameworks/libzcashlc.framework/Info.plist: No such file or directory
--
Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ET3U8b/extracted/Unstoppable D.app/Frameworks/libzcashlc.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ET3U8b/extracted/Unstoppable D.app/Frameworks/libzcashlc.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ET3U8b/extracted/Unstoppable D.app/Frameworks/libzcashlc.framework/Info.plist: No such file or directory
Domain: MIInstallerErrorDomain
Code: 35
User Info: {
    FunctionName = "-[MIBundle _validateWithError:]";
    LegacyErrorString = PackageInspectionFailed;
    SourceFileLine = 64;
}

```

System Information
macOS Version 14.4.1 (Build 23E224)
Xcode 15.3 (22618) (Build 15E204a)
Timestamp: 2024-04-02T17:03:25+06:00

Similar situations can be found on GitHub. Perhaps this will help you:
https://github.com/googleads/swift-package-manager-google-user-messaging-platform/issues/8

**Comment by LukasKorba** [comment]
@str4d I’ve been investigating this issue we face but has been also reported by Pacu (on behalf of Unstoppable)

Long story short, seems like a bug of Apple and so far the only workaround seems to be [this](https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62#issuecomment-1981219533)

We can’t build Zashi because of FFI library, I think adding [MinimumOSVersion](https://developer.apple.com/documentation/bundleresources/information_property_list/minimumosversion) into [info.plist](https://github.com/Electric-Coin-Company/zcash-light-client-ffi/blob/main/support/Info.plist) could be the workaround we need

**Comment by str4d** [comment]
In a pairing with @nuttycom I reverse-engineered the bugfix from the Firebase iOS SDK:
- https://github.com/firebase/firebase-ios-sdk/pull/12243
  - This PR removed the `Info.plist` files from the platform frameworks (`NAME.xcframework/PLATFORM/NAME.framework/Info.plist`), with the rationale that static XCFrameworks containing privacy manifests should be embedded in XCode 15.
  - AFAICT we've never had such files in the `zcash-light-client-ffi` XCFramework.
- https://github.com/firebase/firebase-ios-sdk/pull/12396
  - This PR reverted the first one, due to XCode 15.3 errors of missing `Info.plist` files (https://github.com/firebase/firebase-ios-sdk/issues/12390).
  - This is the same error @pacu, @LukasKorba etc. were seeing above.
- https://github.com/firebase/firebase-ios-sdk/pull/12414
  - This PR appears to replace their self-generated `Info.plist` for the platform frameworks with one sourced from somewhere in XCode, to make it more accurate. I haven't figured out where this file comes from yet.
- https://github.com/firebase/firebase-ios-sdk/pull/12439
  - This contains the other half of the fix: adding the `MinimumOSVersion` key to the `Info.plist` for the platform frameworks (not the root XCFramework `Info.plist` that @LukasKorba suggested above).

https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2020589166 provides an explanation for why an `Info.plist` for the platform frameworks is necessary:
> After our further investigation, we have discovered a possible bug in Xcode 15.3 build system. When compiling a project with a statically linked framework, if we open the app bundle from the archive, we can see a Frameworks folder with a dummy AppsFlyerLib.framework, which is approximately 45 KB in size. For statically linked frameworks, such a folder should not exist. I suspect that when we push the build to the App Store Connect, it tries to validate the .plist of this dummy binary.

My hypothesis is that the `MinimumOSVersion` key works around the bug by enabling us to provide a dummy `Info.plist` that gets included alongside (and validates for) the dummy framework, and then is completely ignored (due to being for a "more recent" OS version than any that exist).

Local experimentation appears to indicate that the following dummy `Info.plist` is sufficient to pass validation (for our -ffi XCFramework):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleExecutable</key>
        <string>libzcashlc</string>
        <key>CFBundleIdentifier</key>
        <string>libzcashlc</string>
        <key>CFBundleName</key>
        <string>libzcashlc</string>
        <key>CFBundlePackageType</key>
        <string>BNDL</string>
        <key>CFBundleVersion</key>
        <string>0.7.5</string>
        <key>CFBundleSupportedPlatforms</key>
        <array>
                <string>iphonesimulator</string>
        </array>
        <key>MinimumOSVersion</key>
        <string>100.0</string>
</dict>
</plist>
```

**Comment by str4d** [comment]
https://github.com/Electric-Coin-Company/zcash-light-client-ffi/pull/135 loads the above `Info.plist` into the FFI XCFramework.

**Comment by LukasKorba** [comment]
Resolved in the latest [release](https://github.com/Electric-Coin-Company/zashi-ios/releases/tag/1.0.5-4)
