### ISSUE TITLE
Syncing to restore wallet isn't working

### ISSUE THREAD

**Issue by miguelaferreira** [Electric-Coin-Company/zashi-ios#1241]
### Describe the issue

After installing the app, I tried to restore my wallet and the process gets stuck on Syncing. I've tried different server choices and the result is the same. The sync never gets past 0.1%, even after 2 hours.

#### If so, please list the steps to reproduce below:
1. Install the app
2. Restore a wallet
3. Watch the syncing progress bar not moving

### Expected behaviour
I would expect that the syncing would make some progress and eventually finish. After which I would expect to be able to see the assets on my wallet, transactions, etc.

### Actual behaviour + errors
The syncing percentage and progress bar do not move beyond 0.1%.

- App Version: 1.0.6
- iOS Version: 17.4.1 (21E236)
- Device: iPhone 13 mini

### Any extra information that might be useful in the debugging process.
Nothing.

**Comment by LukasKorba** [comment]
Birthday very likely hasn't been set, resulting is download & scan the whole chain, that means to start at sapling activation height. The wallet is newer I believe so there are 1-1.5M blocks that are processed with no impact on the actual wallet. That's why 0.1% is shows and takes hours before the % starts moving. 2hrs is very low number, I would expect 10+hrs to see some % progress. This is no "bug", the optimization is to always use birthday of the wallet - to lower the time to sync and to see actual progress relevant for the wallet.
