### ISSUE TITLE
Auto-suggested words have spaces inserted into them in memo and seed phrase text areas.

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zashi-ios#829]
I've noticed this a number of times, where when using auto-suggested tokens there is a space inserted before the last character of the word.

**Comment by LukasKorba** [comment]
I believe you talk about system auto-suggestions? The bubble that from time to time appears and you can tap on it so the word is filled in automatically? If YES, then this is totally out of our control. What Apple/system decides to put to the text field is up to it. 

So this is either unfixable or some regex/logic would need to be implemented that checks number of spaces and reduces it to 1 if > 1. I see no other option.

**Comment by LukasKorba** [comment]
Maybe another option is to turn off the system suggestions on the textfield. I see it should be possible. I remember a request to suggest words from the hardcoded dictionary, if we craft some UI, this could work all together.

1. disable system suggestions 
2. implement custom suggestions from a given dict

**Comment by LukasKorba** [comment]
Resolved in #882 and #883 (first fixes the message-memo box and 2nd fixes the the seed box). Custom solution was needed because system suggestions alongside with custom-TCA binding didn't work well for whatever reason. I used system binding and passing the updated values to the TCA. That way everything works as previously, test included. It's basically a workaround of bypassing.

**Comment by nuttycom** [comment]
Fixed in https://github.com/Electric-Coin-Company/zashi-ios/releases/tag/0.2.0-9
