### ISSUE TITLE
Set final privacy policy URL for iOS

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zashi-ios#940]
The privacy policy links redirects the app to the safari but the URL we have right now is not the final one.

**Comment by LukasKorba** [comment]
https://electriccoin.co/wp-content/uploads/2024/02/Feb-20-24-Zashi-Terms-and-Privacy-Policy.pdf

**Comment by true-jared** [comment]
@LukasKorba The URL we have previously added has been rejected by PlayStore because they do not accept a hosted pdf file. We changed it to this one for now: https://electriccoin.co/zashi-privacy-policy/. In case you wish to update it and keep the same URL on Android and iOS. I will also update it in AppStore console once we pull the 1.0 build and decide to resubmit.
